spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wishlist_database
    username: "{cipher}279ae33b213334931c15f8cadca71c1282e1eec4bd968dcc9e2a15149f18c55b"
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
