spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_database?useSSL=false&serverTimezone=UTC
    username: link
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
