spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_database?useSSL=false&serverTimezone=UTC
    username: '{cipher}49cc4e0161f3cbc1dd57086f64686ec5db68bc7c5f32fa77a74045142e08ec8b'
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
